# Generated by Django 2.1.3 on 2018-11-23 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('clearance', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseID', models.IntegerField(default=0)),
                ('coursename', models.CharField(max_length=20)),
                ('professor', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Labs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LabID', models.IntegerField(default=0)),
                ('courseID', models.CharField(max_length=20)),
                ('tausername', models.CharField(max_length=20)),
            ],
        ),
    ]
